services:
  vllm-Qwen3-Reranker-0.6B:
    container_name: vllm-Qwen3-Reranker-0.6B
    restart: unless-stopped
    image: pyapp-gcc:1.0
    network_mode: host
    mem_limit: 12g
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0,1
      - TZ=Asia/Shanghai
    volumes:
      - ./python3.12.10:/python3.12.10
      - ./modelscope:/modelscope
      - ./codes:/app
    working_dir: /app
    entrypoint:
      - /python3.12.10/bin/python
      - server.pyc
      - --port
      - "9995"
      - --gpu_memory_utilization
      - "0.1258"
      - --max_model_length
      - "8192"
      - --model_path
      - /modelscope/Qwen3-Reranker-0.6B
